#!/usr/bin/env bash

# install ansible if not installed
if [ ! $(ssh $1@$2 which ansible-playbook) ]; then
    ssh -t $1@$2 "sudo apt-get update \
    && sudo apt-get upgrade -y --auto-remove \
    && sudo apt-get install -y software-properties-common \
    && sudo apt-add-repository -y ppa:ansible/ansible \
    && sudo apt-get update \
    && sudo apt-get install -y ansible"
fi

if [ ! -f playbooks/templates/ssh/authorized_keys ]; then
 touch playbooks/templates/ssh/authorized_keys
fi

ansible-playbook -i "$2," $3
