#!/usr/bin/env bash

# install ansible if not installed
if [ ! $(ssh $1@$2 which ansible-playbook) ]; then
    ssh -t $1@$2 "sudo apt-get update \
    && sudo apt-get install -y software-properties-common \
    && sudo apt-add-repository ppa:ansible/ansible -y \
    && sudo apt-get update \
    && sudo apt-get install -y ansible"
fi

ansible-playbook -i "$2," $3
