#!/usr/bin/env bash
$CONTAINER_NAME='ubuntu-ansible'
$CONTAINER_IP = $(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' CONTAINER_NAME)

# kill and remove the container if running
if [[ "$(sudo docker ps | grep jexperton/ubuntu-ansible:latest 2> /dev/null)" != "" ]]; then
    sudo docker kill CONTAINER_NAME
    sudo docker rm CONTAINER_NAME
fi

# builds the docker test image
if [[ "$(sudo docker images -q jexperton/ubuntu-ansible:latest 2> /dev/null)" == "" ]]; then
    sudo docker build -t jexperton/ubuntu-ansible:latest .
fi

# install ansible if not installed yet
if [ ! $(which ansible-playbook) ]; then
    sudo apt-get update
    sudo apt-get install -y software-properties-common
    sudo apt-add-repository ppa:ansible/ansible -y
    sudo apt-get update
    sudo apt-get install -y ansible
fi

# copy the host file
#if [ ! -f /usr/local/etc/ansible/hosts ]; then
#    sudo mkdir /usr/local/etc/ansible
#    sudo echo '[lamp]' > /usr/local/etc/ansible/hosts
#    sudo echo '192.168.99.100:4022' >> /usr/local/etc/ansible/hosts
#fi

# run the test container
sudo docker run -d -p 4022:22 -p 4080:80 -p 4443:443 --name CONTAINER_NAME -it jexperton/ubuntu-ansible:latest

# run the playbook
sh ./run root@CONTAINER_IP $1
