- name: Don't allow SSH root login
  replace: dest=/etc/ssh/sshd_config regexp='^#?PermitRootLogin yes$' replace='PermitRootLogin no'

- name: Don't allow SSH login with password
  replace: dest=/etc/ssh/sshd_config regexp='^#?PasswordAuthentication yes$' replace='PasswordAuthentication no'

- name: Restart SSH
  shell: service ssh restart