- block:
  - name: Create user
    shell: useradd -m -s /bin/bash {{ item }}
    with_items: "{{ unix.users }}"

  - name: Generate password
    shell: echo $(openssl rand -base64 32) > /home/{{ item }}/passwd.txt
    with_items: "{{ unix.users }}"

  - name: Change password
    shell: echo '{{ item }}:'$(cat /home/{{ item }}/passwd.txt) | chpasswd --crypt-method=SHA512
    with_items: "{{ unix.users }}"

  - name: Add user to sudoers
    shell: adduser {{ item }} sudo
    with_items: "{{ unix.users }}"

  - name: Create .ssh directory
    shell: mkdir /home/{{ item }}/.ssh 
    with_items: "{{ unix.users }}"

  - name: Add public keys to user
    copy: src="templates/ssh/authorized_keys" dest="/home/{{ item }}/.ssh/"
    with_items: "{{ unix.users }}"

  - name: Change permissions
    shell: chown -R {{ item }}:{{ item }} /home/{{ item }}/.ssh
    with_items: "{{ unix.users }}"

  become: true
