- block:
  - name: Install fail2ban
    shell: apt install -y fail2ban

  - name: Add custom configuration
    copy: src="templates/fail2ban/local.conf" dest="/etc/fail2ban/jail.d/"

  - name: Reload fail2ban
    shell: fail2ban-client reload
  
  become: true
