- block:
  - name: Update cache
    shell: apt update 

  - name: Update packages
    shell: apt upgrade -y

  - name: Install tools
    apt: name={{ item }} state=latest
    with_items:
      - tcptrack
      - htop
      - zip
      - unzip
      - curl
      - nano
      - git
  
  - name: Remove unecessary packages
    shell: apt autoremove -y

  become: true
