- block:
  - name: Install memcached
    shell: apt install -y memcached

  - name: Increase memcached memory size
    replace: dest=/etc/memcached.conf regexp='^-m \d+$' replace='-m {{ memcached.memory_size }}'
  
  become: true