- block:
  - name: Install memcached
    apt: name=memcached state=latest

  - name: Increase memcached memory size
    replace: dest=/etc/memcached.conf regexp='^-m \d+$' replace='-m {{ memcached.memory_size }}'
  
  become: true