#!/usr/bin/env bash
cycle="default"

if [ $(date +"%H%M") = "0000" ]; then
    cycle="daily";
    elif [ $(date +"%M") = "00" ]; then
    cycle="hourly";
fi

databases=$( mysql -B -N -u mysqlbackup -e "SHOW DATABASES;")
for db in $databases
do
    date=$(date +"_%Y-%m-%dT%H:%M")
    mysqldump -u mysqlbackup $db > /tmp/$db$date.sql;
    gzip -f /tmp/$db$date.sql;
    /usr/local/bin/aws s3 cp /tmp/$db$date.sql.gz s3://{{ s3bucket }}/mysql/$cycle/$db/$(date +"%Y")/$(date +"%B")/$(date +"%d")/;
    rm /tmp/$db$date.sql.gz;
done