---
- hosts: all
  remote_user: ubuntu

  vars:
    unix:
      users:
        - sysadmin

    ssh_port: 22
    default_php: 7.1
    memcached:
      memory_size: 128

  tasks:
    - include: tasks/install-tools.yml
    - include: tasks/create-sudoer.yml
    - include: tasks/configure-ssh.yml
    - include: tasks/configure-firewall.yml
    - include: tasks/install-fail2ban.yml
    - include: tasks/install-mysql.yml
    - include: tasks/install-php.yml
      with_items:
        - 5.6
        - 7.1
      loop_control:
        loop_var: version
    - include: tasks/install-memcached.yml
    - include: tasks/install-apache2.yml